docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Intro: intro.md
    - Usage: usage.md
site_name: laminas-uri
site_description: laminas-uri
repo_url: 'https://github.com/laminas/laminas-uri'
